# Generated by Django 5.0.7 on 2024-07-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_life_product_mfd_product_stock_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='This is the Vendor!', max_length=10000),
        ),
    ]
