# Generated by Django 5.0.7 on 2024-08-03 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_tags_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='City', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='+123 456 789', max_length=1024),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='NYC', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=50),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.product'),
        ),
    ]
