# Generated by Django 5.0.7 on 2024-08-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_cartorder_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
